### ISSUE TITLE
Ändern der GUI

### ISSUE THREAD

**Issue by Hopfenmann** [patrickhofmann0/camera-view-app#2]
Ich stelle mir die Anzeige der Bilder im Web wie folgt vor:
![image](https://github.com/patrickhofmann0/camera-view-app/assets/56252899/9c09d8d0-a7ce-4dad-a159-df0624883243)

- imageListe aufbohren: Uhrzeit, Bild, Link zur Videodatei (erstmal mit platzhaltern bis daten verfügbar)
- add query param filter on date + Datepicker (?) . Paging boxen entfernen  
- template ergänzen analog Bild

**Comment by patrickhofmann0** [comment]
@Hopfenmann das bild kann ich nicht aufrufen?
